/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ApexLegendsRPTracker;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	Library.writeToJson(12);
    }
}
